import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "@/styles/globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import GoogleAdsTracking from "@/components/GoogleAdsTracking";
import { ColorProvider } from "@/providers/ColorProvider";
import Analytics from "@/components/Analytics";

// Font sans-serif (al posto di Geist)
const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Font monospace (al posto di Geist_Mono)
const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleAdsTracking />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ColorProvider>
            <Analytics />
            {children}
          </ColorProvider>
        </AuthProvider>
      </body>
    </html>
  );
}